### PR TITLE
make events page better

### LINKED ISSUE #101: Events datepicker has unclear purpose
image

Is that a filter for start time? End time? Events occurring over that period? No idea whatsoever just from looking at it.

### PR DESCRIPTION
**Pull request by schneider-clarisse**
fixes #101 and #107

### CODE REVIEW

**Comment by StevenLocke** [comment]
Look good to me. One thought, we might want to include the year in the detailed event page, I thought there was a bug with the filtering because the "Yesterday" event happens in 2018.

**Comment by schneider-clarisse** [comment]
Yea, that particular event also has a start date that is later than its end date......

**Comment by schneider-clarisse** [comment]
tbh @StevenLocke i don't think it would be an issue except for our crappy dummy data

**Comment by StevenLocke** [comment]
Agreed. I doubt there are many multi-year conferences.

**Review by StevenLocke — APPROVED** [review]

**Pull request merged**
